version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:alpine
    env_file:
      - ./.env
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: {}
